app/experimental/forms.py
from flask import url_for
from flask_wtf import FlaskForm
from wtforms import ValidationError
from wtforms import (
    BooleanField,
    PasswordField,
    StringField,
    TextAreaField,
    SubmitField,
    SelectField,
)
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, EqualTo, InputRequired, Length

class SelectOralHistory(FlaskForm):
    choice = SelectField(coerce=int)

class AddNewEntityForm(FlaskForm):
    name = StringField('Name', validators=[InputRequired()])
    description = StringField('Description')
    wikipedia_page_title = StringField('Wikipedia page title')

    submit = SubmitField('Submit')

class AddNewEntityMetadataForm(FlaskForm):
    type_ = StringField('Type', validators=[InputRequired()])
    description = StringField('Description')
    submit = SubmitField('Submit')

app/experimental/__init__.py
from app.experimental.views import experimental

app/experimental/views.py
from __future__ import unicode_literals
import os
import json
from flask import Blueprint, render_template, url_for, redirect, current_app, jsonify, flash, request
from flask_login import current_user, login_required

from app import db
from app.models import EditableHTML, OralHistory, WikipediaSuggest, Entity, EntityMeta
from app.wikipedia import search_wikipedia

from app.experimental.forms import SelectOralHistory, AddNewEntityForm, AddNewEntityMetadataForm

experimental = Blueprint('experimental', __name__)

def full_name(oral_history):
    return "{} {}".format(oral_history.first_name, oral_history.last_name)

@experimental.route('/wikipedia', methods=['GET', 'POST'])
@login_required
def wikipedia():
    # data = search_wikipedia('Julia Levy')
    data = []
    form = SelectOralHistory()
    oral_histories = OralHistory.query.all()
    form.choice.choices = []
    oh_id = None
    for oh in oral_histories:
        if (not oh.entity.wikipedia_suggest) or (any([ws.confirmed==False for ws in oh.entity.wikipedia_suggest])):
            form.choice.choices.append((oh.id, full_name(oh)))
    if form.validate_on_submit():
        oh = OralHistory.query.get(form.choice.data)
        oh_id = oh.id
        flash(full_name(oh), 'info')
        data = search_wikipedia(full_name(oh))
        # return render_template('experimental/wikipedia.html', form=form, data=data)
    return render_template(
        'experimental/wikipedia.html', form=form, data=data, oh_id=oh_id)

@experimental.route('/wikipedia/_change_confirm', methods=['POST'])
@login_required
def wikipedia_change_confirm():
    oh_id = request.values.get('oh_id')
    oh = OralHistory.query.get(oh_id)
    ws = WikipediaSuggest.query.filter_by(entity_id=oh.entity.id).one_or_none()
    checked = request.values.get('checked') == 'true'
    wikipedia_page_id = request.values.get('wikipedia_page_id')
    wikipedia_page_title = request.values.get('wikipedia_page_title')
    if ws:
        ws.wikipedia_page_id = wikipedia_page_id
        ws.wikipedia_page_title = wikipedia_page_title
        ws.checked = checked
    else:
        ws = WikipediaSuggest(entity_id=oh.entity.id,
                                wikipedia_page_id=wikipedia_page_id,
                                wikipedia_page_title=wikipedia_page_title,
                                confirmed=checked)
    db.session.add(ws)
    db.session.commit()
    return json.dumps({'success':True}), 200, {'ContentType':'application/json'}

@experimental.route('/wikipedia_suggest', methods=['GET', 'POST'])
@login_required
def wikipedia_suggest():
    wss = WikipediaSuggest.query.filter_by(confirmed=False).all()
    return render_template(
        'experimental/wikipedia_suggest.html', wss=wss)

@experimental.route('/wikipedia_suggest/_change_confirm', methods=['POST'])
@login_required
def wikipedia_suggest_change_confirm():
    ws_id = request.values.get('wikipedia_suggest_id')
    checked = request.values.get('checked') == 'true'
    ws = WikipediaSuggest.query.get(ws_id)
    ws.confirmed = checked
    db.session.add(ws)
    db.session.commit()
    return json.dumps({'success':True}), 200, {'ContentType':'application/json'}

@experimental.route('/add_new_entity', methods=['GET', 'POST'])
@login_required
def add_new_entity():
    form = AddNewEntityForm()
    if form.validate_on_submit():
        if Entity.query.filter_by(name=form.name.data).one_or_none():
            flash('entity with that name already exists', 'error')
        else:
            entity = Entity(name=form.name.data, description=form.description.data)
            db.session.add(entity)
            db.session.flush()
            entity_id = entity.id
            entity_name = entity.name
            wikipedia_page_title = form.wikipedia_page_title.data
            if wikipedia_page_title:
                # if the user entered a url, just get the page title
                if wikipedia_page_title.startswith('http'):
                    wikipedia_page_title = wikipedia_page_title.split('/')[-1]
                ws = WikipediaSuggest(entity_id=entity_id, wikipedia_page_title=wikipedia_page_title, confirmed=True)
                db.session.add(ws)
                wikipedia_added = True
            else:
                wikipedia_added = False

            db.session.commit()

            if wikipedia_added is True:
                flash('added entity {} (id {}) (with Wikipedia link)'.format(entity_name, entity_id), 'info')
            else:
                flash('added entity {} (id {})'.format(entity_name, entity_id), 'info')
    return render_template('experimental/add_new_entity.html', form=form)

@experimental.route('/add_new_entity_metadata/<entity_id>', methods=['GET', 'POST'])
@login_required
def add_new_entity_metadata(entity_id):
    form = AddNewEntityMetadataForm()
    entity = Entity.query.get(entity_id)
    if form.validate_on_submit():
        if EntityMeta.query.filter_by(type_=form.type_.data).filter_by(description=form.description.data).one_or_none():
            flash('this entity metadata already exists', 'error')
        else:
            entity_meta = EntityMeta(entity_id=entity_id, type_=form.type_.data, description=form.description.data)
            db.session.add(entity_meta)
            db.session.flush()
            entity_meta_id = entity_meta.id

            db.session.commit()

            flash('added entity metadata row (id {})'.format(entity_meta_id), 'info')
    return render_template('experimental/add_new_entity_metadata.html', form=form, entity=entity)

@experimental.route('/scratch')
def scratch():
    # data = EntityMeta.query.all()
    import boto3
    s3 = boto3.resource('s3')
    s3_obj = file_content = s3.Object('datalab-projects', 'science-history-institute/entities_counts.tsv')
    file_content = s3_obj.get()['Body'].read().decode('utf-8')
    data = []
    for line in file_content.split('\n'):
        if line:
            line = line.strip().split('\t')
            data.append(line[1])
    return render_template('experimental/scratch.html', data=data)

app/templates/experimental/add_new_entity.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
<div class="ui text container">
	{{ f.render_form(form) }}
</div>
{% endblock %}

app/templates/experimental/add_new_entity_metadata.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
<h1>Add new entity metadata for entity "{{ entity.name }}"</h1>
<div class="ui text container">
	{{ f.render_form(form) }}
</div>
{% endblock %}

app/templates/experimental/scratch.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="ui text container">
	{% for item in data %}
	<p>{{ item }}</p>
	{% endfor %}
</div>
{% endblock %}

app/templates/experimental/wikipedia.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
<div class="ui text container">
	{{ f.render_form(form, extra_classes='name_select_form') }}
	{% for item in data %}
	<p><a href="http://en.wikipedia.org/wiki/{{ item.title }}" target="_blank">{{ item.title }}</a></p>
	<p>{{ item.snippet }}</p>
															<input type="checkbox" name="confirmed" 
														  data-pageid="{{item.pageid}}"
														  data-pagetitle="{{item.title}}"
															class="ws-confirmed">
	{% endfor %}
</div>
<script type="text/javascript" charset="utf-8">
	$( document ).ready(function() {
		console.log($('.name_select_form select'));
		// Submit form immediately on change
		$('.name_select_form select').change(function() {
			// $(this).closest('form').trigger('submit');
			$(this).closest('form').submit();
		})

						$('.ws-confirmed').change(function(event) {
							var checkbox = event.target;
							console.log(checkbox);
							console.log(checkbox.dataset.id);
							$.ajax({
								url: '{{ url_for("experimental.wikipedia_change_confirm") }}',
								type: 'POST',
								dataType: 'json',
								headers: {
									'X-CSRF-Token': '{{ csrf_token() }}'
								},
								data: {
									oh_id: '{{ oh_id }}',
									checked: checkbox.checked,
									wikipedia_page_id: checkbox.dataset.pageid,
									wikipedia_page_title: checkbox.dataset.pagetitle,
								},
								error: function (jqXHR, textStatus, errorThrown) {
									console.log(jqXHR);
									console.log(textStatus);
									console.log(errorThrown);
								},
							});
						});
	});
</script>
{% endblock %}

app/templates/experimental/wikipedia_suggest.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui stackable grid container">
        <div class="sixteen wide tablet twelve wide computer centered column">
            <h2 class="ui header">
							Wikipedia suggestions
            </h2>

            <div class="ui menu">
                <div class="ui search item">
                    <div class="ui transparent icon input">
                        <input id="search-wikipedia-suggest" type="text" placeholder="Search…">
                        <i class="search icon"></i>
                    </div>
                </div>
            </div>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable celled table">
                    <thead>
                        <tr>
                            <th>Entity Name</th>
                            <th>Wikipedia page title</th>
                            <th>Confirmed</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in wss %}
												<tr>

                            <td>{{ item.entity.name }}</td>
                            <td><a href="http://en.wikipedia.org/wiki/{{ item.wikipedia_page_title}}" target="_blank">{{ item.wikipedia_page_title }}</a></td>
														<td>
															<input type="checkbox" name="confirmed" 
														  data-id="{{item.id}}"
														  {% if item.confirmed==True %}
															checked
														  {% endif %} 
															class="ws-confirmed">
														</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-wikipedia-suggest').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });


						$('.ws-confirmed').change(function(event) {
							var checkbox = event.target;
							console.log(checkbox);
							console.log(checkbox.dataset.id);
							$.ajax({
								url: '{{ url_for("experimental.wikipedia_suggest_change_confirm") }}',
								type: 'POST',
								dataType: 'json',
								headers: {
									'X-CSRF-Token': '{{ csrf_token() }}'
								},
								data: {wikipedia_suggest_id: checkbox.dataset.id,
									checked: checkbox.checked},
								error: function (jqXHR, textStatus, errorThrown) {
									console.log(jqXHR);
									console.log(textStatus);
									console.log(errorThrown);
								},
							});
						});

        });

    </script>
{% endblock %}